name: Setup K8s Diff tools
description: Installs all k8s-diff tools to the PATH
runs:
  using: "composite"
  steps:
    - run: |
        set -e
        cd ${{ github.action_path }}/..
        go build -o bin/ ./cmd/...
        echo $PWD/bin >> $GITHUB_PATH
      shell: bash